[project]
name = "python-universe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "plotly>=5.24.1",
    "pywebio>=1.8.3",
    "pyyaml>=6.0.2",
    "requests>=2.32.3",
]
